trigger: none

pool:
  vmImage: ubuntu-latest

variables:
- name: deploymentDefaultLocation
  value: westus3

stages:

- stage: Test
  jobs:
  - job: TestJob
    steps:
    - script: echo "Test stage passed"

- stage: DeployUS
  jobs:
  - job: 'DeployUSJob'
    steps:
    - script: |
        echo "Forcing DeployUS stage to fail"
        exit 1

- stage: DeployEurope
  jobs:
  - job: DeployEuropeJob
    steps:
    - script: echo "DeployEurope stage"
