trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: JobA
  displayName: 'Job A'
  steps:
  - script: |
      echo "Job A is running temp"
      sleep 10
    displayName: 'Run Job A'

- job: JobB
  displayName: 'Job B'
  steps:
  - script: |
      echo "Job B is running temp"
      sleep 10
    displayName: 'Run Job B'
  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      feedsToUse: 'select'
